### ISSUE TITLE
mitos_error

### ISSUE THREAD

**Issue by ivaneskos** [gavieira/mitos2_wrapper#2]
Hi @gavieira!

I have that error after launching your code. Maybe you have any ideas where it came from?

Running MITOS for file /media/ivan/HDD2TB/ivan/Desktop/Neuchatel/ascomycota_project/mt_genomes/AP024451.fasta...
An error has occurred for this annotation/gbk conversion process: 'module' object has no attribute 'run'

FULL ERROR:

Traceback (most recent call last):
  File "/media/ivan/HDD2TB/ivan/Desktop/Neuchatel/ascomycota_project/scripts/mitos2_wrapper/mitos2_wrapper.py", line 172, in <module>
    annotation.run_mitos()
  File "/media/ivan/HDD2TB/ivan/Desktop/Neuchatel/ascomycota_project/scripts/mitos2_wrapper/mitos2_wrapper.py", line 81, in run_mitos
    mitos = subprocess.run(["runmitos.py", "-i", self.fasta, "-c", str(self.gencode), "-o", self.results, "-r", self.refdir, "--linear", "--ncbicode", "--noplots", "--best", "--alarab", "--intron", "0", "--oril", "0", "--orih", "0"], stdout=output, stderr=error)
AttributeError: 'module' object has no attribute 'run'

Thank you in advance for your response!

**Comment by gavieira** [comment]
Hi, @ivaneskos!

Sorry for the late reply. 

Are you running this script on python>=3.5? Apparently, the `subprocess.run()` function is [not available before that version](https://stackoverflow.com/questions/40590192/getting-an-error-attributeerror-module-object-has-no-attribute-run-while).


Also, for the record: MITOS2 updates changed its available options, making this script not compatible with newer releases. In order for the script to work, please use mitos=2.0.3. You can install it using bioconda.
