### ISSUE TITLE
FASTA_mitos/result.bed file not found

### ISSUE THREAD

**Issue by imogen-foote** [gavieira/mitos2_wrapper#3]
I am trying to run this for the first time and I am encountering the below error. The FASTA_mitos directory and the .gbk file are both being created but both empty. Any idea's what's going wrong? Thanks in advance. 
```
Running MITOS for file FASTA...
Finished MITOS with exit status 1
All features were succesfully annotated
Generating file FASTA.gbk...
An error has occurred for this annotation/gbk conversion process: [Errno 2] No such file or directory: 'FASTA_mitos/result.bed'

FULL ERROR:

Traceback (most recent call last):
  File "/nesi/nobackup/vuw03922/scripts/Chapter3/extract_mitogenome/mitos2_wrapper.py", line 173, in <module>
    annotation.generate_gbk()
  File "/nesi/nobackup/vuw03922/scripts/Chapter3/extract_mitogenome/mitos2_wrapper.py", line 100, in generate_gbk
    gbk.write(self.format_features() + self.format_sequence())
  File "/nesi/nobackup/vuw03922/scripts/Chapter3/extract_mitogenome/mitos2_wrapper.py", line 105, in format_features
    with open(self.bed_file) as bed:
FileNotFoundError: [Errno 2] No such file or directory: 'FASTA_mitos/result.bed'
```

**Comment by gavieira** [comment]
Hi, @imogen-foote !

I'm really sorry, but I honestly have no idea how to fix it. Actually, this code is so old that it would be better to just write a new wrapper for scratch, but unfortunately I haven't got the time to do so for the time being.

So, the best I can do for now is point out to #2, maybe it could help fix the error?

Sorry for not being able to help more and happy new year!
